### PR TITLE
Allow reference sequence to be returned always as upper case.

### PR DESCRIPTION
**Pull request by mattions**
This is just a merge request to allow to return the sequence always as upper case, both in the raw and in the sequence format.

We have this user case in our case.

### CODE REVIEW

**Comment by mdshw5** [comment]
Thanks for the pull request. If you add a test case for this (maybe [here](https://github.com/mdshw5/pyfaidx/blob/master/tests/test_FastaRecord.py#L19)) then I'll merge and push a new PyPI release. It would also be great if you document this feature in the Readme.

**Comment by mattions** [comment]
As data tests, 
is ok if I add a small bit of the hs37d5 in the data repo, or should I download the whole thing from somewhere and add it to the `download_gene_fasta.py` ?

I'm downloading the gens right now, if there is already an example with smaller case I could use that directly.

**Comment by mdshw5** [comment]
The script that generates the test data now generates a file called "genes.fasta.lower". This file should work for testing your contribution. You don't even have to test against a particular sequence, you could:

```python
assert Fasta(sequence_always_upper=True)['gi|557361099|gb|KF435150.1|'] == Fasta()['gi|557361099|gb|KF435150.1|'].seq.upper()
```
and do the same for the `as_raw` case.

**Comment by mattions** [comment]
@mdshw5 I have updated the test to use `genes.fasta.lower` (and also make sure it gets created if you do not have it on the disk already.)

README updated with the example.

Should go green.

**Comment by mdshw5** [comment]
Looks great - thanks for the contribution!

**Comment by mattions** [comment]
do you have an idea when the next release with this fix will be out?

**Comment by mdshw5** [comment]
Thanks for reminding me. I just pushed the release through CI. When the tests pass a new version will be pushed to PyPI. Should happen some time this morning.

**Comment by mdshw5** [comment]
Looks like it's done.

**Pull request merged**
