### PR TITLE
implement Sequence.__eq__

### PR DESCRIPTION
**Pull request by Maarten-vd-Sande**
Pretty self-explanatory. Now we can directly compare pyfaidx.Sequence to strings.

### CODE REVIEW

**Comment by mdshw5** [comment]
Looks fantastic. Thanks for the contribution!

**Comment by mdshw5** [comment]
This will show up in PyPI as "0.5.8" as soon as the CI server releases the tagged commit.

**Comment by Maarten-vd-Sande** [comment]
@mdshw5 I think you forgot to merge :angel:

**Comment by mdshw5** [comment]
Oh man. Thanks - I'll re-tag and re-release.

**Pull request merged**
