### PR TITLE
pathlib.Path can be passed to Fasta and Faidx

### PR DESCRIPTION
**Pull request by palao**
This PR concerns issue #183 
I wasn't sure about where to write the tests so I added a new file. Also I would like to know your opinion about how the test this thing: is the proposed test enough?

### CODE REVIEW

**Comment by mdshw5** [comment]
Closing a re-opening to trigger CI

**Comment by mdshw5** [comment]
Hey @palao thanks for contributing. As you can see I re-wrote the tests when I found out that `nose` is no longer supported. I've edited your tests (thank you) to adapt them to `pytest`, and have also realized that GH actions isn't triggering on pull requests properly. I'll try to get tests running and merge this as soon as possible.

**Comment by palao** [comment]
Hi @mdshw5 . It was my bad: I used master as the base branch of my changes. I thought I was already in develop...
(indeed I wanted to suggest switching to pytest :rofl: )

**Comment by mdshw5** [comment]
No It was my bad. I was pushing to master, and you correctly contributed against develop. I quickly rebased develop so your PR would make sense. I like pytest so far and should have switched earlier. It's disappointing that I've had to switch both CI providers and test frameworks in the past year, but I guess nothing lasts forever...

**Comment by mdshw5** [comment]
Thanks for the contribution @palao. I'll tag a new release asap.

**Pull request merged**
