### PR TITLE
Consolidate long name methods to all use `long_name`

### PR DESCRIPTION
**Pull request by michaelbarton**

### CODE REVIEW

**Comment by michaelbarton** [comment]
How is this? I think this is what you requested.

**Comment by mdshw5** [comment]
Hey @michaelbarton. This looks like a great contribution, and I have no problem merging it. Thanks for taking the time to make the change - I'll push out a new minor version!

**Comment by michaelbarton** [comment]
Thanks Matt for this library. I have been using it recently a project and I
found it very useful. https://gitlab.com/michaelbarton/gaet/

**Comment by mdshw5** [comment]
Looks like a pretty cool tool you've got there. The idea is the assess the quality of assemblies based on previous feature annotation? What's a common use case?

**Comment by michaelbarton** [comment]
Yes that's exactly it. If you have a reference assembly and you want to
benchmark an assembler you can compare the generated assembly's annotations
with that of the reference's annotation. We're using it to determine which
assemblers produce complete rRNA operons and so forth.

For example we genomes for which we have both pacbio and illumina sequencing
data. We use the pacbio assembly as the reference since they are generally
very high quality, then benchmark various assemblers using the illumina data.

**Pull request merged**
